### PR TITLE
[Fixed] #3

### PR DESCRIPTION
**Pull request by Kristinita**
I get some error like **#3**, extracting package solved my problem.

You may solved this problem without user actions. If you will have `.no-sublime-package` file in root directory of your package, package will install to `Packages/{Package Name}/` folder. See [**Packed vs Unpacked**](https://packagecontrol.io/docs/customizing_packages).

Thanks.

### CODE REVIEW

**Comment by robinchenyu** [comment]
This works, Thanks

**Comment by Kristinita** [comment]
@robinchenyu , if this works, why you don't merge changes 😕 ?

Thanks.

**Comment by robinchenyu** [comment]
Already merged, Pls try.

Thanks!

**Review by robinchenyu — COMMENTED** [review]
thanks

**Pull request closed without merging**
